In [1]:
import numpy as np
a = [[11 , 12, 13], \
    [21, 22, 23], \
    [31, 32, 33]]

a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [3]:
A = np.array(a)
print(A , A.ndim, A.shape, A.size, A.dtype)

[[11 12 13]
 [21 22 23]
 [31 32 33]] 2 (3, 3) 9 int64


In [5]:
# Access the element on the second row and third column
A[1, 2]

np.int64(23)

In [6]:
# Access the element on the second row and third column
A[1][2]

np.int64(23)

In [8]:
# Access the element on the first row and first and second columns
A[0][0:2]

array([11, 12])