In [2]:
import numpy as np
a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [3]:
print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: 2
a[3]: 3
a[4]: 4


In [4]:
print(np.__version__)

2.4.2


In [5]:
type(a)

numpy.ndarray

In [6]:
a.dtype

dtype('int64')

In [7]:
a.shape

(5,)

In [8]:
len(a)

5

In [9]:
a = np.array(range(10))
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
b = np.array([10, 20, 30, 40, 50, 60, 70])
print( b.shape, b.size, len(b), b.dtype, b.ndim)

(7,) 7 7 int64 1


In [11]:
a = np.array([1, -1, 1, -1])

print(a.mean(),  a.std(), a.max(), a.min())

0.0 1.0 1 -1


In [12]:
u = np.array([1, 0])
v = np.array([0, 1])

print(np.add(u, v),  u+1)

[1 1] [2 1]


In [13]:
l = np.linspace(-2, 2, 9)
l

array([-2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ])